CREATE DATABASE dbQuanLyCafe
GO
USE dbQuanLyCafe
GO
CREATE TABLE NhanVien
(
	MaNV VARCHAR(32) PRIMARY KEY NOT NULL,
	TenNV NVARCHAR(256) NOT NULL,
	MatKhau NVARCHAR(256),
	SDT VARCHAR(16),
	DiaChi NVARCHAR(256)
)
GO
INSERT INTO NhanVien(MaNV,TenNV,MatKhau) VALUES('ADMIN','ADMIN','123')
GO
GO
CREATE TABLE Ban
(
	MaBan VARCHAR(32) PRIMARY KEY NOT NULL,
	SucChua INT NOT NULL,
	TrangThai INT 
)
GO
INSERT INTO Ban(MaBan,SucChua,TrangThai) VALUES('BAN1',4,0)
INSERT INTO Ban(MaBan,SucChua,TrangThai) VALUES('BAN2',4,0)
INSERT INTO Ban(MaBan,SucChua,TrangThai) VALUES('BAN3',4,0)
INSERT INTO Ban(MaBan,SucChua,TrangThai) VALUES('BAN4',4,0)
INSERT INTO Ban(MaBan,SucChua,TrangThai) VALUES('BAN5',4,0)
INSERT INTO Ban(MaBan,SucChua,TrangThai) VALUES('BAN6',4,0)
INSERT INTO Ban(MaBan,SucChua,TrangThai) VALUES('BAN7',4,0)
GO
CREATE TABLE KhachHang
(
	MaKH VARCHAR(32) PRIMARY KEY NOT NULL,
	TenKH NVARCHAR(256) NOT NULL,
	SDT VARCHAR(16),
	DiaChi NVARCHAR(256)
)
GO
INSERT INTO KhachHang(MaKH,TenKH) VALUES('KHACHVANGLAI',N'Khách vãng lai')
GO
CREATE TABLE LoaiDoUong 
(
	MaLoai VARCHAR(32) PRIMARY KEY NOT NULL,
	TenLoai NVARCHAR(256) NOT NULL
)
GO
INSERT INTO LoaiDoUong(MaLoai,TenLoai) VALUES('CAFE',N'Cafe')
INSERT INTO LoaiDoUong(MaLoai,TenLoai) VALUES('TRASUA',N'Trà sữa')
GO
CREATE TABLE DoUong 
(
	MaDU VARCHAR(32) PRIMARY KEY NOT NULL,
	TenDU NVARCHAR(256) NOT NULL,
	MaLoai VARCHAR(32) references LoaiDoUong(MaLoai),
	DonGia DECIMAL,
	HinhAnh NVARCHAR(MAX)
)
GO
INSERT INTO DoUong(MaDU,TenDU,MaLoai,DonGia,HinhAnh) VALUES('CAFEDA',N'CAFE đá','CAFE',12000)
INSERT INTO DoUong(MaDU,TenDU,MaLoai,DonGia,HinhAnh) VALUES('CAFESUA',N'CAFE sữa','CAFE',15000)
INSERT INTO DoUong(MaDU,TenDU,MaLoai,DonGia,HinhAnh) VALUES('CAFECACAO',N'CAFE ca cao','CAFE',25000)
GO
CREATE TABLE HoaDon
(
	MaHD VARCHAR(32) PRIMARY KEY NOT NULL,
	NgayLap DATETIME,
	MaNV VARCHAR(32) references NhanVien(MaNV),
	MaKH VARCHAR(32) references KhachHang(MaKH),
	MaBan VARCHAR(32) references Ban(MaBan),
	TongTien DECIMAL,
	TrangThai BIT
)
GO
CREATE TABLE ChiTietHoaDon
(
	MaHD VARCHAR(32) references HoaDon(MaHD),
	MaDU VARCHAR(32) references DoUong(MaDU),
	SoLuong DECIMAL,
	DonGia DECIMAL,
	ThanhTien DECIMAL
)